Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.define "ivkvm_ubuntu2004" do |ivkvm|
      ivkvm.vm.box = "ubuntu/focal64"
      # Ubuntu 5.4.0-135.152-generic 5.4.212
      ivkvm.vm.box_version = "20221213.0.0"
      
      ivkvm.vm.synced_folder "../..", "/ivkvm/kvm-introvirt"
      ivkvm.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/playbooks/ivkvm.yml"
        # ansible.verbose = "vvv"
      end
    end
  end
