Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.define "ivkvmhost_ubuntu2004" do |ivkvmhost|
      ivkvmhost.vm.box = "ubuntu/focal64"
      # Ubuntu 5.4.0-135.152-generic 5.4.212
      ivkvmhost.vm.box_version = "20221213.0.0"
  
      ivkvmhost.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/playbooks/ivkvmhost.yml"
        # ansible.verbose = "vvv"
      end
    end
  end
