Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.define "ivkvmhostci_ubuntu2004" do |ivkvmhostci|
      ivkvmhostci.vm.box = "LethalServant/ivkvmhost"
      ivkvmhostci.vm.box_version = "0.1.1"
  
      ivkvmhostci.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/playbooks/ivkvmhostci.yml"
        # ansible.verbose = "vvv"
      end
    end
  end